-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Config Hyprland (Lua) — voir https://wiki.hypr.land/Configuring/Start/
-- Réorganisé et commenté pour plus de lisibilité.
--
-- Sommaire :
--   1. Moniteurs
--   2. Programmes / commandes personnalisées
--   3. Autostart
--   4. Variables d'environnement
--   5. Permissions
--   6. Apparence (general / decoration / animations)
--   7. Règles de workspace
--   8. Layouts (dwindle / master / scrolling)
--   9. Divers
--  10. Input (clavier / trackpad / trackpoint / gestes)
--  11. Raccourcis clavier (par catégorie)
--  12. Règles de fenêtres / calques

------------------------------------------------------------
-- 1. MONITEURS
-- https://wiki.hypr.land/Configuring/Basics/Monitors/
------------------------------------------------------------

hl.monitor({
	output = "", -- "" = s'applique à tous les moniteurs non configurés explicitement
	mode = "1920x1080@60.Hz",
	position = "auto",
	scale = "1",
})

------------------------------------------------------------
-- 2. PROGRAMMES / COMMANDES PERSONNALISÉES
-- Centralise ici les commandes réutilisées plus bas dans les
-- raccourcis clavier, pour ne les modifier qu'à un seul endroit.
------------------------------------------------------------

local terminal = "kitty"
local fileManager = "nemo"
local browser = "firefox"
local menurun = "rofi -show combi -modes combi -combi-modes 'windows,drun,run' -display-combi ' '"

-- Screenshot d'une zone sélectionnée (grim + slurp), enregistré en JPEG horodaté.
local take_a_screenshot =
	"mkdir -p ~/Images/Screenshots && grim -g \"$(slurp)\" -t jpeg -q 50 ~/Images/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').jpeg"

-- Redémarre Waybar (utile après un changement de config/CSS).
local reload_waybar = "killall waybar && waybar"

-- Bascule le verrou anti-veille (voir hypridle.conf : condition_cmd
-- vérifie l'existence de ce fichier avant de suspendre la machine).
local toggle_idle_inhibit = os.getenv("HOME") .. "/.config/hypr/scripts/toggle-idle-inhibit.sh"

------------------------------------------------------------
-- 3. AUTOSTART
-- https://wiki.hypr.land/Configuring/Basics/Autostart/
------------------------------------------------------------

hl.on("hyprland.start", function()
	-- hl.exec_cmd(terminal)
	-- hl.exec_cmd("nm-applet")

	hl.exec_cmd("waybar & hyprpaper") -- barre de statut + fond d'écran
	hl.exec_cmd("hypridle") -- gestion de l'inactivité / veille
	hl.exec_cmd("systemctl --user enable --now hyprpolkitagent.service") -- agent d'authentification graphique
	hl.exec_cmd("wl-paste --type text --watch cliphist store") -- historique presse-papiers (texte)
	hl.exec_cmd("wl-paste --type image --watch cliphist store") -- historique presse-papiers (images)
end)

------------------------------------------------------------
-- 4. VARIABLES D'ENVIRONNEMENT
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
------------------------------------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

------------------------------------------------------------
-- 5. PERMISSIONS
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Nécessite un redémarrage de Hyprland (pas de hot-reload, pour des
-- raisons de sécurité).
------------------------------------------------------------

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

------------------------------------------------------------
-- 6. APPARENCE
-- https://wiki.hypr.land/Configuring/Basics/Variables/
------------------------------------------------------------

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 10,

		border_size = 1,

		col = {
			active_border = "rgba(8caaeeff)",
			--inactive_border = "rgba(595959aa)",
			inactive_border = "rgba(59595900)",
		},

		resize_on_border = false, -- redimensionner en cliquant-glissant sur les bordures

		-- Voir https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ avant d'activer.
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2.0,

		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = true,
			range = 20,
			render_power = 1,
			color = "#00000088",
			color_inactive = "#00000000",
		},

		blur = {
			enabled = true,
			size = 1,
			passes = 4,
			vibrancy = 0.0,
			brightness = 0.5,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Courbes et animations par défaut.
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("bounce", { type = "bezier", points = { { 0.68, -0.6 }, { 0.32, 1.6 } } })

hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 1, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 2, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 2, bezier = "easeOutQuint", style = "popin 50%" })
-- hl.animation({ leaf = "windowsIn", enabled = true, speed = 1, spring = "easy", style = "popin 87%" })
-- hl.animation({ leaf = "windowsOut", enabled = true, speed = 1, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 1, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 2, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 2, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 2, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 2, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 2, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3, bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 2, bezier = "quick" })

------------------------------------------------------------
-- 7. RÈGLES DE WORKSPACE
-- https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / pas de gaps quand une seule fenêtre — décommenter
-- tout le bloc si souhaité.
------------------------------------------------------------

-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

------------------------------------------------------------
-- 8. LAYOUTS
------------------------------------------------------------

-- Dwindle — https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/
hl.config({
	dwindle = {
		preserve_split = true, -- recommandé
	},
})

-- Master — https://wiki.hypr.land/Configuring/Layouts/Master-Layout/
hl.config({
	master = {
		new_status = "master",
	},
})

-- Scrolling — https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

------------------------------------------------------------
-- 9. DIVERS
------------------------------------------------------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- 0/1 pour désactiver la mascotte animée
		disable_hyprland_logo = false, -- true = désactive le fond d'écran logo/anime aléatoire
	},
})

------------------------------------------------------------
-- 10. INPUT
------------------------------------------------------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "qwerty-fr",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,

		touchpad = {
			natural_scroll = true,
			scroll_factor = 0.7,
			disable_while_typing = true,
		},
	},
})

-- Trackpoint (ex. ThinkPad).
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
hl.device({
	name = "tpps/2-elan-trackpoint",
	sensitivity = 0.7,
	accel_profile = "flat",
})

-- Geste 3 doigts horizontal = changement de workspace.
hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

------------------------------------------------------------
-- 11. RACCOURCIS CLAVIER
-- https://wiki.hypr.land/Configuring/Basics/Binds/
------------------------------------------------------------

local mainMod = "SUPER" -- touche "Windows" comme modificateur principal

-- ---- Applications ----

hl.bind(mainMod .. " + return ", hl.dsp.exec_cmd(terminal)) -- ouvrir le terminal
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager)) -- ouvrir le gestionnaire de fichiers
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser)) -- ouvrir le navigateur
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd(menurun)) -- lanceur d'applications (rofi)

-- ---- Fenêtres ----

local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close()) -- fermer la fenêtre active
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" })) -- flottant on/off
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- mode pseudo (dwindle)
hl.bind(mainMod .. " + O", hl.dsp.layout("togglesplit")) -- inverser le split (dwindle uniquement)
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" })) -- plein écran

-- Déplacer le focus avec mainMod + flèches (HJKL, style Vim)
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Déplacer/redimensionner une fenêtre avec mainMod + clic gauche/droit + glisser
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ---- Workspaces ----

-- Basculer vers / déplacer une fenêtre vers un workspace avec mainMod (+ SHIFT) + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 correspond à la touche 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Workspace spécial (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Défiler entre les workspaces avec mainMod + molette
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- ---- Système / outils ----

hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(reload_waybar)) -- redémarrer Waybar
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd(take_a_screenshot)) -- capture d'écran (zone)
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd(toggle_idle_inhibit)) -- bascule anti-veille

hl.bind(
	mainMod .. " + SHIFT + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
) -- menu d'extinction / déconnexion

hl.bind(
	"XF86PowerOff",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"),
	{ locked = true }
) -- touche dédiée power off (fonctionne même écran verrouillé)

-- ---- Touches multimédias (clavier / portable) ----

hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Nécessite playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

------------------------------------------------------------
-- 12. RÈGLES DE FENÊTRES / CALQUES
-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
------------------------------------------------------------

-- Ignorer les demandes de maximisation de toutes les applis (généralement souhaitable).
local suppressMaximizeRule = hl.window_rule({
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

-- Corrige des soucis de drag avec XWayland.
hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Les règles de calque (layer_rule) renvoient aussi un handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Fenêtre de hyprland-run : position flottante en bas à gauche.
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})
