general {
    lock_cmd = pkill -x hyprlock; hyprlock
    #unlock_cmd = notify-send "unlock!"      # same as above, but unlock
    before_sleep_cmd = loginctl lock-session
    #after_sleep_cmd = notify-send "Awake!"  # command ran after sleep
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false          # whether to ignore systemd-inhibit --what=idle inhibitors
}

# Baisser la luminosité de l'écran au bout de 2 minutes.
listener {
    timeout = 120                            # in seconds
    condition_cmd = [ ! -f $HOME/.cache/hypridle_inhibit.lock ] # check if idle is locked
    condition_retry = 30
    on-timeout = brightness_inactive on # command to run when timeout has passed
    on-resume = brightness_inactive off# command to run when activity is detected after timeout has fired.
}

# Mettre en veille au bout de 4 minutes.
listener {
    timeout = 240                            # in seconds
    condition_cmd = [ ! -f $HOME/.cache/hypridle_inhibit.lock ] # check if idle is locked
    condition_retry = 30
    on-timeout = systemctl suspend # command to run when timeout has passed
    on-resume = brightnessctl set 100%  # command to run when activity is detected after timeout has fired.
}
